const ASSET_STRING = {
	BG_120X120: "BG_120X120",
	BG_270X270: "BG_360X270",

	BOILING_POT: "BOILING_POT",
	SKILLET: "SKILLET",
	STEAMER: "STEAMER",
	DEEP_FRYER: "DEEP_FRYER",

	BOIL_COOKING_STYLE: "BOIL_COOKING_STYLE",

	CRATE: "CRATE",
	PLATE: "PLATE",
	CHOPPING_BOARD: "CHOPPING_BOARD",

	RAW_FISH: "RAW_FISH",
	CHOPPED_FISH: "CHOPPED_RAW_FISH",
	FRIED_FISH: "FRIED_FISH",
	STEAMED_FISH: "STEAMED_FISH",

	NORI: "NORI",

	RAW_RICE: "RAW_RICE",
	STEAMED_RICE: "STEAMED_RICE",

	FISH_MAKI: "FISH_MAKI",
	SASHIMI: "SASHIMI",
};

export default ASSET_STRING;
