const ASSET_STRING = {
	// Others
	BG_120X120: "BG_120X120",
	BG_270X270: "BG_360X270",
	HIGHLIGHT: "HIGHLIGHT",

	// Cookwares
	BOILING_POT: "BOILING_POT",
	SKILLET: "SKILLET",
	STEAMER: "STEAMER",
	DEEP_FRYER: "DEEP_FRYER",
	CRATE: "CRATE",
	PLATE: "PLATE",
	CHOPPING_BOARD: "CHOPPING_BOARD",
	BOIL_COOKING_STYLE: "BOIL_COOKING_STYLE",

	// Dishes
	FISH_MAKI: "FISH_MAKI",
	SASHIMI: "SASHIMI",

	// Ingredients
	FISH: "FISH",
	RICE: "RICE",
	NORI: "NORI",
};

export default ASSET_STRING;
